module.exports = {
  tt0421715: {
  imdbID: "tt0421715",
  Title: "The Curious Case of Benjamin Button",
  Released: "2008-12-25",
  Runtime: 166,
  Genres: ["Drama", "Fantasy", "Romance"],
  Directors: ["David Fincher"],
  Writers: ["Eric Roth", "Robin Swicord", "F. Scott Fitzgerald"],
  Actors: ["Brad Pitt", "Cate Blanchett", "Tilda Swinton"],
  Plot: "Benjamin Button, born in 1918 with the physical state of an elderly man, ages in reverse. He experiences love and break-ups, ecstasy and sorrow, and timelessness by the time he dies in 2003 as a baby.",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BYjIyNDExOWItM2Y4ZC00NmY3LWFlN2ItYTJlZDQ1NTJlZTUwXkEyXkFqcGc@._V1_SX300.jpg",
  Metascore: 70,
  imdbRating: 7.8,
},
tt5164214: {
  imdbID: "tt5164214",
  Title: "Ocean's Eight",
  Released: "2018-06-08",
  Runtime: 110,
  Genres: ["Action", "Comedy", "Crime"],
  Directors: ["Gary Ross"],
  Writers: ["Gary Ross", "Olivia Milch", "George Clayton Johnson"],
  Actors: ["Sandra Bullock", "Cate Blanchett", "Anne Hathaway"],
  Plot: "Debbie Ocean gathers an all-female crew to attempt an impossible heist at New York City's annual Met Gala.",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BMjAyNDEyMzc4Ml5BMl5BanBnXkFtZTgwMjEzNjM0NTM@._V1_SX300.jpg",
  Metascore: 61,
  imdbRating: 6.3,
},
  tt2334873: {
  imdbID: "tt2334873",
  Title: "Blue Jasmine",
  Released: "2013-08-23",
  Runtime: 98,
  Genres: ["Comedy", "Drama", "Romance"],
  Directors: ["Woody Allen"],
  Writers: ["Woody Allen"],
  Actors: ["Cate Blanchett", "Joy Carlin", "Richard Conti"],
  Plot: "A New York socialite, deeply troubled and in denial, arrives in San Francisco to impose upon her sister. She looks like a million dollars but isn't bringing money, peace or love.",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BMTc0ODk5MzEyMV5BMl5BanBnXkFtZTcwMzI0MDY1OQ@@._V1_SX300.jpg",
  Metascore: 78,
  imdbRating: 7.3,
},
tt3501632: {
  imdbID: "tt3501632",
  Title: "Thor: Ragnarok",
  Released: "2017-11-03",
  Runtime: 130,
  Genres: ["Action", "Adventure", "Comedy"],
  Directors: ["Taika Waititi"],
  Writers: ["Eric Pearson", "Craig Kyle", "Christopher Yost"],
  Actors: ["Chris Hemsworth", "Tom Hiddleston", "Cate Blanchett"],
  Plot: "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_QL75_UX380_CR0,0,380,562_.jpg",
  Metascore: 74,
  imdbRating: 7.9,
},
  tt0084787: {
    imdbID: "tt0084787",
    Title: "The Thing",
    Released: "1982-06-25",
    Runtime: 109,
    Genres: ["Horror", "Mystery", "Sci-Fi"],
    Directors: ["John Carpenter"],
    Writers: ["Bill Lancaster", "John W. Campbell Jr."],
    Actors: ["Kurt Russell", "Wilford Brimley", "Keith David"],
    Plot: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGViZWZmM2EtNGYzZi00ZDAyLTk3ODMtNzIyZTBjN2Y1NmM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    Metascore: 57,
    imdbRating: 8.2,
  },
  tt0120737: {
    imdbID: "tt0120737",
    Title: "The Lord of the Rings: The Fellowship of the Ring",
    Released: "2001-12-19",
    Runtime: 178,
    Genres: ["Action", "Adventure", "Drama"],
    Directors: ["Peter Jackson"],
    Writers: ["J.R.R. Tolkien", "Fran Walsh", "Philippa Boyens"],
    Actors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    Plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
    Metascore: 92,
    imdbRating: 8.8,
  },
  tt0085959: {
    imdbID: "tt0085959",
    Title: "The Meaning of Life",
    Released: "1983-03-31",
    Runtime: 107,
    Genres: ["Comedy", "Musical"],
    Directors: ["Terry Jones", "Terry Gilliam"],
    Writers: ["Graham Chapman", "John Cleese", "Terry Gilliam"],
    Actors: ["John Cleese", "Terry Gilliam", "Eric Idle"],
    Plot: "The comedy team takes a look at life in all of its stages in their own uniquely silly way.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWJkNGY5MDAtYmVkMy00NzdiLTk5MzctMzA0MjMxMDY2NGYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Metascore: 72,
    imdbRating: 7.5,
  },
  tt0107048: {
    imdbID: "tt0107048",
    Title: "Groundhog Day",
    Released: "1993-02-12",
    Runtime: 101,
    Genres: ["Comedy", "Drama", "Fantasy"],
    Directors: ["Harold Ramis"],
    Writers: ["Danny Rubin", "Harold Ramis"],
    Actors: ["Bill Murray", "Andie MacDowell", "Chris Elliott"],
    Plot: "A narcissistic, self-centered weatherman finds himself in a time loop on Groundhog Day, and the day keeps repeating until he gets it right.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWIxNzM5YzQtY2FmMS00Yjc3LWI1ZjUtNGVjMjMzZTIxZTIxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Metascore: 72,
    imdbRating: 8.1,
  },
  tt0124315: {
    imdbID: "tt0124315",
    Title: "The Cider House Rules",
    Released: "2000-01-07",
    Runtime: 126,
    Genres: ["Drama", "Romance"],
    Directors: ["Lasse Hallström"],
    Writers: ["John Irving"],
    Actors: ["Tobey Maguire", "Charlize Theron", "Michael Caine"],
    Plot: "A compassionate young man, raised in an orphanage and trained to be a doctor there, decides to leave to see the world.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmY5YzA4OTQtOTQzZS00NDZmLTlhNzQtNzk5NTIyZWE2ZjVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Metascore: 75,
    imdbRating: 7.4,
  },
  tt0248808: {
    imdbID: "tt0248808",
    Title: "For the Birds",
    Released: "2001-11-02",
    Runtime: 3,
    Genres: ["Animation", "Short", "Comedy"],
    Directors: ["Ralph Eggleston"],
    Writers: ["Ralph Eggleston"],
    Actors: ["Ralph Eggleston"],
    Plot: "A group of snooty birds roosting on a telephone wire get their just deserts when a goofy bird drops in.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjBhYzgyY2YtMTBhZS00NWIwLWIyYTgtMzhhYmFhZDNkMTQxXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_SX300.jpg",
    Metascore: 0.1,
    imdbRating: 8.0,
  }
};
